#REST
rest :
  type: rest
  resource: "routing_rest.yml"
  prefix : /api


cop_categories_db:
    path: /{locale}/znx/db/category/{search}/{page}
    defaults: { _controller: CopApiBundle:ProductCategoryDb:index , _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"

cop_categories_api:
    path: /{locale}/sdc/api/category/{search}/{page}
    defaults: { _controller: CopApiBundle:ProductCategoryApi:index , _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"

cop_categories_api_chief:
    path: /{locale}/blender/category/{search}/{page}
    defaults: { _controller: CopApiBundle:ProductCategory:index , _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"


cop_categories:
    path: /{_locale}/category/{slug}/{page}
    defaults: { _controller: CopCategoriesBundle:Categories:index , _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

product_home:
    path: /{_locale}/home/{page}
    defaults: { _controller: CopHomeBundle:Home:index,  _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"

product_home_api:
    path:     /home/products/{search}
    defaults: { _controller: CopApiBundle:ProductHome:index }

product_api:
    path:     /home/products/sdc/api/{_locale}/{search}/{page}
    defaults: { _controller: CopApiBundle:ProductHomeApi:index,  _locale: fr, page: 1  }
    requirements:
        _locale: "%app.locales%"

product_db:
    path:     /home/products/znx/db/{_locale}/{search}
    defaults: { _controller: CopApiBundle:ProductHomeDb:index,  _locale: fr }
    requirements:
        _locale: "%app.locales%"

cop_import:
    resource: "@CopImportBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cop_common:
    resource: "@CopCommonBundle/Controller/"
    type:     annotation

app_homepage_translated:
    resource: "@CopHomeBundle/Controller/HomeController.php"
    type:     annotation

app_api_by_term:
    resource: "@CopCommonBundle/Controller/SearchController.php"
    type:     annotation
