#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api


product_home:
    path:     /home/products/{search}
    defaults: { _controller: CopApiBundle:ProductHome:index }

product_api:
    path:     /home/products/sdc/api/fr/
    defaults: { _controller: CopApiBundle:ProductApi:index }

product_db:
    path:     /home/products/znx/db/fr/{search}
    defaults: { _controller: CopApiBundle:ProductDb:index }


cop_import:
    resource: "@CopImportBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cop_common:
    resource: "@CopCommonBundle/Controller/"
    type:     annotation

app_homepage_translated:
    resource: "@CopHomeBundle/Controller/HomeController.php"
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"