<?php

namespace Cop\DataStoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WhiteListCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhiteListCategoriesRepository extends EntityRepository
{

}
