#src/Obtao/UserBundle/Resources/config/routing_rest.yml
api_product_home :
  type: rest
  resource: "CopApiBundle:ProductHomeDbRest"
  name_prefix:  api_
api_category :
  type: rest
  resource: "CopApiBundle:ProductCategoryDbRest"
  name_prefix:  api_